### ISSUE TITLE
Lapis Carrot Removes Markings

### ISSUE THREAD

**Issue by BJTMastermind** [BJTMastermind/HorseFood#1]
Pulled from upstream issue: [#2](https://github.com/LothrazarMinecraftMods/HorseFood/issues/2) posted by [Svedrigailov](https://github.com/Svedrigailov)
---
This is a small issue, but likely important for many. If you use the lapis carrot on a horse with markings, spots for example, and you cycle through all the colors, the markings get removed.

To clarify, you start with a black horse with white spots, if you use the carrot on it until it goes back to black, the spots will disappear.

I think it would be better for horses to retain their markings.

**Comment by VoxelBill** [comment]
Fixed.
